# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

#default_platform(:ios)

#Sameer on 17/3/25
#platform :ios do
#  desc "Push a new beta build to TestFlight"
#  lane :beta do
#    increment_build_number(xcodeproj: "InstaCashSDK.xcodeproj")
#    build_app(workspace: "InstaCashSDK.xcworkspace", scheme: "InstaCashSDK")
#    upload_to_testflight
#  end
#end



# Uncomment the line if you want fastlane to automatically update itself
#update_fastlane
#opt_out_usage


#key_id: APPLE_KEY_ID,
#issuer_id: APPLE_ISSUER_ID,
#key_content: APPLE_KEY_CONTENT,
#key_id: ENV["APPLE_KEY_ID"],
#issuer_id: ENV["APPLE_ISSUER_ID"],
#key_content: ENV["APPLE_KEY_CONTENT"],    
#key_filepath: "/Users/sameerkhan/Downloads/InstaCashSDK/fastlane/AuthKey_DVM2UH7XLT.p8",


default_platform(:ios)

APPLE_KEY_ID = ENV["APPLE_KEY_ID"]
APPLE_ISSUER_ID = ENV["APPLE_ISSUER_ID"]
APPLE_KEY_CONTENT = ENV["APPLE_KEY_CONTENT"]


DEVELOPER_APP_ID = ENV["DEVELOPER_APP_ID"]
DEVELOPER_APP_IDENTIFIER = ENV["DEVELOPER_APP_IDENTIFIER"]
MATCH_PASSWORD = ENV["MATCH_PASSWORD"]
PROVISIONING_PROFILE_SPECIFIER = ENV["PROVISIONING_PROFILE_SPECIFIER"]
TEMP_KEYCHAIN_USER = ENV["TEMP_KEYCHAIN_USER"]
TEMP_KEYCHAIN_PASSWORD = ENV["TEMP_KEYCHAIN_PASSWORD"]
APPLE_ISSUER_ID = ENV["ASC_ISSUER_ID"]
APPLE_KEY_ID = ENV["ASC_KEY_ID"]
APPLE_KEY_CONTENT = ENV["ASC_KEY"]
GIT_AUTHORIZATION = ENV["GIT_AUTHORIZATION"]
PROVISIONING_PROFILE_ID = ENV["PROVISIONING_PROFILE_ID"]
#FIREBASE_GROUP = ENV["FIREBASE_GROUP"]
#FIREBASE_APP_ID = ENV["FIREBASE_APP_ID"]
#FIREBASE_TOKEN_CLI = ENV["FIREBASE_TOKEN_CLI"]

def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: 0
  )
end

def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

platform :ios do
  lane :upload_ios_beta_Testflight do
    #keychain_name : TEMP_KEYCHAIN_USER,
    #keychain_password : TEMP_KEYCHAIN_PASSWORD,
    keychain_name = ENV["TEMP_KEYCHAIN_USER"]
    keychain_password = ENV["TEMP_KEYCHAIN_PASSWORD"]
    #output_name : "InstaCashSDK",
    #workspace : "InstaCashSDK.xcworkspace",
    ensure_temp_keychain(keychain_name, keychain_password)

    api_key = app_store_connect_api_key(      
      key_id: "DVM2UH7XLT",
      issuer_id: "69a6de95-94e2-47e3-e053-5b8c7c11a4d1",
      key_content: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR1RBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJIa3dkd0lCQVFRZ25ybFJCMy90Ui9hN3VVQ1oKK3FSNndtVVdyY1lvall4ZmZubzc0aWxUdisyZ0NnWUlLb1pJemowREFRZWhSQU5DQUFTbEtKeGxFSExkQ1drRwppaXY5eVR4K3RaU2xNUThNVXZuWDFpSDdHK2szNzRIbVRacUdvVm1KSUxZc1puMlVwTENPN1c3WEpzYzEzSVFjCnk0UE5IMnFyCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=",
      #key_filepath: "/Users/sameerkhan/Downloads/InstaCashSDK/fastlane/AuthKey_DVM2UH7XLT.p8",
      is_key_content_base64: true,       
      duration: 1200,            
      in_house: false
    )
    
    increment_build_number(xcodeproj: "InstaCashSDK.xcodeproj")

    cocoapods(
      clean_install: true
    )

    match(
      type: 'appstore', # can use type like development, app-store, ad-hoc according to the requirement.
      app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
      git_basic_authorization: Base64.strict_encode64(GIT_AUTHORIZATION),
      readonly: true,
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      api_key: api_key
    )

    gym(
      output_name: "InstaCashSDK",
      workspace: "InstaCashSDK.xcworkspace",
      scheme: "InstaCashSDK",
      export_method: "app-store",
      output_directory: "/Users/sameerkhan/Downloads/InstaCashSDK/",
      output_name: "InstaCashSDK.ipa",
      export_options: {
        provisioningProfiles: {
          "in.InstaSDK.InstaCashSDK" => "match AppStore in.InstaSDK.InstaCashSDK"
        },
        xcargs: "IPHONEOS_DEPLOYMENT_TARGET=17.0"
      },
      clean: true
    )

    # gym(
    #   configuration: "Release",
    #   workspace: "InstaCashSDK.xcworkspace",
    #   scheme: "InstaCashSDK",
    #   export_method: "app-store",
    #   export_options: {
    #     provisioningProfiles: {
    #         DEVELOPER_APP_ID => PROVISIONING_PROFILE_SPECIFIER,
    #         DEVELOPER_APP_IDENTIFIER => PROVISIONING_PROFILE_ID
    #     }
    #   }
    # )

    pilot(
      apple_id: "#{DEVELOPER_APP_ID}",
      app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
      skip_waiting_for_build_processing: true,
      skip_submission: true,
      distribute_external: false,
      notify_external_testers: false,
      ipa: "./InstaCashSDK.ipa"
    )

    delete_temp_keychain(keychain_name)
  end
end
